In [1]:
import pandas as pd

df1=pd.read_csv("online_retail_09_10.csv")
df2=pd.read_csv("online_retail_10_11.csv")

df1.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,12/1/2009 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,12/1/2009 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,12/1/2009 7:45,1.25,13085.0,United Kingdom

In [2]:
df2.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [3]:
df = pd.concat([df1,df2], ignore_index=True)
df.shape

(1067371, 8)

In [4]:
df.duplicated().sum()

np.int64(34335)

In [5]:
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      4275
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     235151
Country             0
dtype: int64

In [7]:
df = df.dropna(subset=['CustomerID'])
df.shape

(797885, 8)

In [8]:
df[df['Quantity']<0].shape[0], df[df['UnitPrice']<0].shape[0]

(18390, 0)

In [9]:
df[df['Quantity']<0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,12/1/2009 10:33,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,12/1/2009 10:33,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,12/1/2009 10:33,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,12/1/2009 10:33,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,12/1/2009 10:33,2.95,16321.0,Australia

In [10]:
df['InvoiceNo'].dtype,df['StockCode'].dtype,df['Description'].dtype,df['Quantity'].dtype,df['InvoiceDate'].dtype,df['UnitPrice'].dtype,df['CustomerID'].dtype,df['Country'].dtype

(<StringDtype(storage='python', na_value=nan)>,
 <StringDtype(storage='python', na_value=nan)>,
 <StringDtype(storage='python', na_value=nan)>,
 dtype('int64'),
 <StringDtype(storage='python', na_value=nan)>,
 dtype('float64'),
 dtype('float64'),
 <StringDtype(storage='python', na_value=nan)>)

In [11]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['CustomerID'] = df['CustomerID'].astype(int)

df['InvoiceNo'].dtype,df['StockCode'].dtype,df['Description'].dtype,df['Quantity'].dtype,df['InvoiceDate'].dtype,df['UnitPrice'].dtype,df['CustomerID'].dtype,df['Country'].dtype

(<StringDtype(storage='python', na_value=nan)>,
 <StringDtype(storage='python', na_value=nan)>,
 <StringDtype(storage='python', na_value=nan)>,
 dtype('int64'),
 dtype('<M8[us]'),
 dtype('float64'),
 dtype('int64'),
 <StringDtype(storage='python', na_value=nan)>)

In [12]:
df['TransactionType']=df['Quantity'].apply(lambda x: 'Return' if x<0 else 'Sale')
df['TotalPrice']=df['Quantity'] * df['UnitPrice']

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TransactionType,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,Sale,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,Sale,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,Sale,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,Sale,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,Sale,30.0

In [13]:
df.to_csv('clean_retail.csv',index=False)